# Generated by Django 6.0.5 on 2026-07-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_dismissed',
            field=models.BooleanField(default=False, verbose_name='Приховано користувачем'),
        ),
    ]
