# Generated by Django 6.0.5 on 2026-07-29 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_is_dismissed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва рахунку/картки (напр. Monobank EUR)')),
                ('card_number', models.CharField(max_length=50, verbose_name='Номер картки або IBAN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Картка для оплати',
                'verbose_name_plural': 'Картки для оплати',
            },
        ),
        migrations.CreateModel(
            name='AccountingProxy',
            fields=[
            ],
            options={
                'verbose_name': '📊 Бухгалтерія (Звіт)',
                'verbose_name_plural': '📊 Бухгалтерія (Звіти)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.order',),
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Елемент кошика', 'verbose_name_plural': 'Елементи кошика'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиція замовлення', 'verbose_name_plural': 'Позиції замовлення'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар / Страва', 'verbose_name_plural': 'Товари та Страви'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профіль користувача', 'verbose_name_plural': 'Профілі користувачів'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='orders_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='category_type',
            field=models.CharField(choices=[('base', 'Базова (входить до створення меню)'), ('simple', 'Проста (Заморозка, напої, окремі товари)')], default='base', max_length=10, verbose_name='Тип категорії'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Орієнтовний час доставки від адміна'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Ціна, якщо додається до сформованого меню (€)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='menu_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8, verbose_name='Ціна комплексного меню (€)'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(max_length=100, verbose_name='Бажаний час'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20, verbose_name='Метод оплати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Прийнято'), ('canceled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.foodcategory', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фотографія страви'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Стандартна ціна (€)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва страви'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_or_portion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вага / Порція'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='admin_telegram_ids',
            field=models.CharField(blank=True, default='', help_text='ID адмінів через кому', max_length=255, verbose_name='Telegram ID адмінів'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_regular_customer',
            field=models.BooleanField(default=False, verbose_name='Постійний клієнт'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.paymentcard', verbose_name='Обрана картка'),
        ),
    ]
