# Generated by Django 6.0.5 on 2026-08-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_paymentcard_accountingproxy_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='slug',
            field=models.CharField(choices=[('garnir', 'Гарнір'), ('main', 'Друга страва'), ('soup', 'Суп'), ('salad', 'Салат'), ('other', 'Інше / Прості товари')], default='other', max_length=20, verbose_name='Тип страви для розрахунку сетів'),
        ),
    ]
